<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "facebookpage"
 *
 * Auto generated by Extension Builder 2016-10-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Facebook Page',
	'description' => 'Facebook page extension can be used to embed facebook page to site.Website visitors can Like as well as share the facebook page without leaving the website.',
	'category' => 'plugin',
	'author' => 'Aswathy.S',
	'author_email' => 'aswathy.sh@pitsolutions.com',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.x-8.4.x',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);